name: Hello World CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Print Hello World
        run: |
          cat hello_world.txt